local ResourceData = {
	["Wood"] = {
		DisplayName = "Wood",
		NodeModel = "fallen_log",
		HarvestTime = 3,
		MinYield = 2,
		MaxYield = 4,
		RespawnTime = 60,
	},
	["Cotton"] = {
		DisplayName = "Cotton",
		NodeModel = "cotton_plant",
		HarvestTime = 2,
		MinYield = 1,
		MaxYield = 3,
		RespawnTime = 60,
	},
	["Wild Berries"] = {
		DisplayName = "Wild Berries",
		NodeModel = "berry_bush",
		HarvestTime = 2,
		MinYield = 2,
		MaxYield = 5,
		RespawnTime = 45,
	},
}

return ResourceData
